// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *
 *      Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 *  this list of conditions and the following disclaimer.
 *  Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  Neither the name of the pig4cloud.com developer nor the names of its
 *  contributors may be used to endorse or promote products derived from
 *  this software without specific prior written permission.
 *  Author: lengleng (wangiegie@gmail.com)
 *
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;
import java.time.LocalDateTime;

/**
 * <p>
 * 部门管理
 * </p>
 *
 * @author lengleng
 * @since 2018-01-22
 */
public class Dept extends Model<Dept> {
	@Serial
	private static final long serialVersionUID = 1L;
	@TableId(value = "dept_id", type = IdType.ASSIGN_ID)
	private Long deptId;
	/**
	 * 部门名称
	 */
	private String name;
	/**
	 * 排序
	 */
	private Integer sortOrder;
	/**
	 * 创建人
	 */
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	/**
	 * 修改人
	 */
	@TableField(fill = FieldFill.UPDATE)
	private String updateBy;
	/**
	 * 创建时间
	 */
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	/**
	 * 修改时间
	 */
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;
	/**
	 * 父级部门id
	 */
	private Long parentId;
	/**
	 * 是否删除 1：已删除 0：正常
	 */
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Dept() {
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getDeptId() {
		return this.deptId;
	}

	/**
	 * 部门名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getName() {
		return this.name;
	}

	/**
	 * 排序
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	/**
	 * 修改时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * 父级部门id
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getParentId() {
		return this.parentId;
	}

	/**
	 * 是否删除 1：已删除 0：正常
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDeptId(final Long deptId) {
		this.deptId = deptId;
	}

	/**
	 * 部门名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setName(final String name) {
		this.name = name;
	}

	/**
	 * 排序
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setSortOrder(final Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	/**
	 * 修改时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * 父级部门id
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setParentId(final Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * 是否删除 1：已删除 0：正常
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "Dept(deptId=" + this.getDeptId() + ", name=" + this.getName() + ", sortOrder=" + this.getSortOrder() + ", createBy=" + this.getCreateBy() + ", updateBy=" + this.getUpdateBy() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", parentId=" + this.getParentId() + ", delFlag=" + this.getDelFlag() + ")";
	}


	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public static final class Fields {
		public static final java.lang.String deptId = "deptId";
		public static final java.lang.String name = "name";
		public static final java.lang.String sortOrder = "sortOrder";
		public static final java.lang.String createBy = "createBy";
		public static final java.lang.String updateBy = "updateBy";
		public static final java.lang.String createTime = "createTime";
		public static final java.lang.String updateTime = "updateTime";
		public static final java.lang.String parentId = "parentId";
		public static final java.lang.String delFlag = "delFlag";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Dept)) return false;
		final Dept other = (Dept) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$deptId = this.getDeptId();
		final java.lang.Object other$deptId = other.getDeptId();
		if (this$deptId == null ? other$deptId != null : !this$deptId.equals(other$deptId)) return false;
		final java.lang.Object this$sortOrder = this.getSortOrder();
		final java.lang.Object other$sortOrder = other.getSortOrder();
		if (this$sortOrder == null ? other$sortOrder != null : !this$sortOrder.equals(other$sortOrder)) return false;
		final java.lang.Object this$parentId = this.getParentId();
		final java.lang.Object other$parentId = other.getParentId();
		if (this$parentId == null ? other$parentId != null : !this$parentId.equals(other$parentId)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Dept;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $deptId = this.getDeptId();
		result = result * PRIME + ($deptId == null ? 43 : $deptId.hashCode());
		final java.lang.Object $sortOrder = this.getSortOrder();
		result = result * PRIME + ($sortOrder == null ? 43 : $sortOrder.hashCode());
		final java.lang.Object $parentId = this.getParentId();
		result = result * PRIME + ($parentId == null ? 43 : $parentId.hashCode());
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		return result;
	}
}
