// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *    Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * Neither the name of the pig4cloud.com developer nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * Author: lengleng (wangiegie@gmail.com)
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;
import java.time.LocalDateTime;

/**
 * 字典项
 *
 * @author lengleng
 * @date 2019/03/19
 */
public class DictItem extends Model<DictItem> {
	@Serial
	private static final long serialVersionUID = 1L;
	@TableId
	private Long id;
	private Long dictId;
	private String itemValue;
	private String label;
	private String dictType;
	private String description;
	private Integer sortOrder;
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	@TableField(fill = FieldFill.UPDATE)
	private String updateBy;
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;
	private String remarks;
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public DictItem() {
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getDictId() {
		return this.dictId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getItemValue() {
		return this.itemValue;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getLabel() {
		return this.label;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDictType() {
		return this.dictType;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDescription() {
		return this.description;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getRemarks() {
		return this.remarks;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setId(final Long id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDictId(final Long dictId) {
		this.dictId = dictId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setItemValue(final String itemValue) {
		this.itemValue = itemValue;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setLabel(final String label) {
		this.label = label;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDictType(final String dictType) {
		this.dictType = dictType;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDescription(final String description) {
		this.description = description;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setSortOrder(final Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRemarks(final String remarks) {
		this.remarks = remarks;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "DictItem(id=" + this.getId() + ", dictId=" + this.getDictId() + ", itemValue=" + this.getItemValue() + ", label=" + this.getLabel() + ", dictType=" + this.getDictType() + ", description=" + this.getDescription() + ", sortOrder=" + this.getSortOrder() + ", createBy=" + this.getCreateBy() + ", updateBy=" + this.getUpdateBy() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", remarks=" + this.getRemarks() + ", delFlag=" + this.getDelFlag() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof DictItem)) return false;
		final DictItem other = (DictItem) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$dictId = this.getDictId();
		final java.lang.Object other$dictId = other.getDictId();
		if (this$dictId == null ? other$dictId != null : !this$dictId.equals(other$dictId)) return false;
		final java.lang.Object this$sortOrder = this.getSortOrder();
		final java.lang.Object other$sortOrder = other.getSortOrder();
		if (this$sortOrder == null ? other$sortOrder != null : !this$sortOrder.equals(other$sortOrder)) return false;
		final java.lang.Object this$itemValue = this.getItemValue();
		final java.lang.Object other$itemValue = other.getItemValue();
		if (this$itemValue == null ? other$itemValue != null : !this$itemValue.equals(other$itemValue)) return false;
		final java.lang.Object this$label = this.getLabel();
		final java.lang.Object other$label = other.getLabel();
		if (this$label == null ? other$label != null : !this$label.equals(other$label)) return false;
		final java.lang.Object this$dictType = this.getDictType();
		final java.lang.Object other$dictType = other.getDictType();
		if (this$dictType == null ? other$dictType != null : !this$dictType.equals(other$dictType)) return false;
		final java.lang.Object this$description = this.getDescription();
		final java.lang.Object other$description = other.getDescription();
		if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		final java.lang.Object this$remarks = this.getRemarks();
		final java.lang.Object other$remarks = other.getRemarks();
		if (this$remarks == null ? other$remarks != null : !this$remarks.equals(other$remarks)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof DictItem;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $dictId = this.getDictId();
		result = result * PRIME + ($dictId == null ? 43 : $dictId.hashCode());
		final java.lang.Object $sortOrder = this.getSortOrder();
		result = result * PRIME + ($sortOrder == null ? 43 : $sortOrder.hashCode());
		final java.lang.Object $itemValue = this.getItemValue();
		result = result * PRIME + ($itemValue == null ? 43 : $itemValue.hashCode());
		final java.lang.Object $label = this.getLabel();
		result = result * PRIME + ($label == null ? 43 : $label.hashCode());
		final java.lang.Object $dictType = this.getDictType();
		result = result * PRIME + ($dictType == null ? 43 : $dictType.hashCode());
		final java.lang.Object $description = this.getDescription();
		result = result * PRIME + ($description == null ? 43 : $description.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		final java.lang.Object $remarks = this.getRemarks();
		result = result * PRIME + ($remarks == null ? 43 : $remarks.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		return result;
	}
}
