// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *    Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * Neither the name of the pig4cloud.com developer nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * Author: lengleng (wangiegie@gmail.com)
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;
import java.time.LocalDateTime;

/**
 * 字典表
 *
 * @author lengleng
 * @date 2019/03/19
 */
public class Dict extends Model<Dict> {
	@Serial
	private static final long serialVersionUID = 1L;
	/**
	 * 编号
	 */
	@TableId(type = IdType.ASSIGN_ID)
	private Long id;
	/**
	 * 类型
	 */
	private String dictType;
	/**
	 * 描述
	 */
	private String description;
	/**
	 * 创建时间
	 */
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	/**
	 * 更新时间
	 */
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;
	/**
	 * 是否是系统内置
	 */
	private String systemFlag;
	/**
	 * 备注信息
	 */
	private String remarks;
	/**
	 * 创建人
	 */
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	/**
	 * 修改人
	 */
	@TableField(fill = FieldFill.UPDATE)
	private String updateBy;
	/**
	 * 删除标记
	 */
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Dict() {
	}

	/**
	 * 编号
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getId() {
		return this.id;
	}

	/**
	 * 类型
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDictType() {
		return this.dictType;
	}

	/**
	 * 描述
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDescription() {
		return this.description;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * 是否是系统内置
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getSystemFlag() {
		return this.systemFlag;
	}

	/**
	 * 备注信息
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * 删除标记
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * 编号
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setId(final Long id) {
		this.id = id;
	}

	/**
	 * 类型
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDictType(final String dictType) {
		this.dictType = dictType;
	}

	/**
	 * 描述
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDescription(final String description) {
		this.description = description;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * 是否是系统内置
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setSystemFlag(final String systemFlag) {
		this.systemFlag = systemFlag;
	}

	/**
	 * 备注信息
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRemarks(final String remarks) {
		this.remarks = remarks;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * 删除标记
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "Dict(id=" + this.getId() + ", dictType=" + this.getDictType() + ", description=" + this.getDescription() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", systemFlag=" + this.getSystemFlag() + ", remarks=" + this.getRemarks() + ", createBy=" + this.getCreateBy() + ", updateBy=" + this.getUpdateBy() + ", delFlag=" + this.getDelFlag() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Dict)) return false;
		final Dict other = (Dict) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$dictType = this.getDictType();
		final java.lang.Object other$dictType = other.getDictType();
		if (this$dictType == null ? other$dictType != null : !this$dictType.equals(other$dictType)) return false;
		final java.lang.Object this$description = this.getDescription();
		final java.lang.Object other$description = other.getDescription();
		if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		final java.lang.Object this$systemFlag = this.getSystemFlag();
		final java.lang.Object other$systemFlag = other.getSystemFlag();
		if (this$systemFlag == null ? other$systemFlag != null : !this$systemFlag.equals(other$systemFlag)) return false;
		final java.lang.Object this$remarks = this.getRemarks();
		final java.lang.Object other$remarks = other.getRemarks();
		if (this$remarks == null ? other$remarks != null : !this$remarks.equals(other$remarks)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Dict;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $dictType = this.getDictType();
		result = result * PRIME + ($dictType == null ? 43 : $dictType.hashCode());
		final java.lang.Object $description = this.getDescription();
		result = result * PRIME + ($description == null ? 43 : $description.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		final java.lang.Object $systemFlag = this.getSystemFlag();
		result = result * PRIME + ($systemFlag == null ? 43 : $systemFlag.hashCode());
		final java.lang.Object $remarks = this.getRemarks();
		result = result * PRIME + ($remarks == null ? 43 : $remarks.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		return result;
	}
}
