// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *    Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * Neither the name of the pig4cloud.com developer nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * Author: lengleng (wangiegie@gmail.com)
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;
import java.time.LocalDateTime;

/**
 * 文件管理实体类
 *
 * @author lengleng
 * @date 2025/07/03
 */
public class File extends Model<File> {
	@Serial
	private static final long serialVersionUID = 1L;
	/**
	 * 编号
	 */
	@TableId(type = IdType.ASSIGN_ID)
	private Long id;
	/**
	 * 文件名
	 */
	private String fileName;
	/**
	 * 原文件名
	 */
	private String original;
	/**
	 * 容器名称
	 */
	private String bucketName;
	/**
	 * 文件类型
	 */
	private String type;
	/**
	 * 文件大小
	 */
	private Long fileSize;
	/**
	 * 上传人
	 */
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	/**
	 * 上传时间
	 */
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	/**
	 * 更新人
	 */
	@TableField(fill = FieldFill.INSERT)
	private String updateBy;
	/**
	 * 更新时间
	 */
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;
	/**
	 * 删除标识：1-删除，0-正常
	 */
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public File() {
	}

	/**
	 * 编号
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getId() {
		return this.id;
	}

	/**
	 * 文件名
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getFileName() {
		return this.fileName;
	}

	/**
	 * 原文件名
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getOriginal() {
		return this.original;
	}

	/**
	 * 容器名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getBucketName() {
		return this.bucketName;
	}

	/**
	 * 文件类型
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getType() {
		return this.type;
	}

	/**
	 * 文件大小
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getFileSize() {
		return this.fileSize;
	}

	/**
	 * 上传人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * 上传时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	/**
	 * 更新人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * 删除标识：1-删除，0-正常
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * 编号
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setId(final Long id) {
		this.id = id;
	}

	/**
	 * 文件名
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setFileName(final String fileName) {
		this.fileName = fileName;
	}

	/**
	 * 原文件名
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setOriginal(final String original) {
		this.original = original;
	}

	/**
	 * 容器名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setBucketName(final String bucketName) {
		this.bucketName = bucketName;
	}

	/**
	 * 文件类型
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setType(final String type) {
		this.type = type;
	}

	/**
	 * 文件大小
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setFileSize(final Long fileSize) {
		this.fileSize = fileSize;
	}

	/**
	 * 上传人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	/**
	 * 上传时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	/**
	 * 更新人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * 删除标识：1-删除，0-正常
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "File(id=" + this.getId() + ", fileName=" + this.getFileName() + ", original=" + this.getOriginal() + ", bucketName=" + this.getBucketName() + ", type=" + this.getType() + ", fileSize=" + this.getFileSize() + ", createBy=" + this.getCreateBy() + ", createTime=" + this.getCreateTime() + ", updateBy=" + this.getUpdateBy() + ", updateTime=" + this.getUpdateTime() + ", delFlag=" + this.getDelFlag() + ")";
	}


	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public static final class Fields {
		public static final java.lang.String id = "id";
		public static final java.lang.String fileName = "fileName";
		public static final java.lang.String original = "original";
		public static final java.lang.String bucketName = "bucketName";
		public static final java.lang.String type = "type";
		public static final java.lang.String fileSize = "fileSize";
		public static final java.lang.String createBy = "createBy";
		public static final java.lang.String createTime = "createTime";
		public static final java.lang.String updateBy = "updateBy";
		public static final java.lang.String updateTime = "updateTime";
		public static final java.lang.String delFlag = "delFlag";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof File)) return false;
		final File other = (File) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$fileSize = this.getFileSize();
		final java.lang.Object other$fileSize = other.getFileSize();
		if (this$fileSize == null ? other$fileSize != null : !this$fileSize.equals(other$fileSize)) return false;
		final java.lang.Object this$fileName = this.getFileName();
		final java.lang.Object other$fileName = other.getFileName();
		if (this$fileName == null ? other$fileName != null : !this$fileName.equals(other$fileName)) return false;
		final java.lang.Object this$original = this.getOriginal();
		final java.lang.Object other$original = other.getOriginal();
		if (this$original == null ? other$original != null : !this$original.equals(other$original)) return false;
		final java.lang.Object this$bucketName = this.getBucketName();
		final java.lang.Object other$bucketName = other.getBucketName();
		if (this$bucketName == null ? other$bucketName != null : !this$bucketName.equals(other$bucketName)) return false;
		final java.lang.Object this$type = this.getType();
		final java.lang.Object other$type = other.getType();
		if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof File;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $fileSize = this.getFileSize();
		result = result * PRIME + ($fileSize == null ? 43 : $fileSize.hashCode());
		final java.lang.Object $fileName = this.getFileName();
		result = result * PRIME + ($fileName == null ? 43 : $fileName.hashCode());
		final java.lang.Object $original = this.getOriginal();
		result = result * PRIME + ($original == null ? 43 : $original.hashCode());
		final java.lang.Object $bucketName = this.getBucketName();
		result = result * PRIME + ($bucketName == null ? 43 : $bucketName.hashCode());
		final java.lang.Object $type = this.getType();
		result = result * PRIME + ($type == null ? 43 : $type.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		return result;
	}
}
