// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *
 *      Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 *  this list of conditions and the following disclaimer.
 *  Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  Neither the name of the pig4cloud.com developer nor the names of its
 *  contributors may be used to endorse or promote products derived from
 *  this software without specific prior written permission.
 *  Author: lengleng (wangiegie@gmail.com)
 *
 */
package com.pig4cloud.pig.sys.entity;

import cn.idev.excel.annotation.ExcelIgnore;
import cn.idev.excel.annotation.ExcelProperty;
import com.baomidou.mybatisplus.annotation.*;
import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * <p>
 * 日志表
 * </p>
 *
 * @author lengleng
 * @since 2017-11-20
 */
public class Log implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;
	@TableId(type = IdType.ASSIGN_ID)
	@ExcelProperty("日志编号")
	private Long id;
	@ExcelProperty("日志类型（0-正常 9-错误）")
	private String logType;
	@ExcelProperty("日志标题")
	private String title;
	@ExcelProperty("创建人")
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	@ExcelProperty("创建时间")
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	@ExcelIgnore
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;
	@ExcelProperty("操作ip地址")
	private String remoteAddr;
	private String userAgent;
	@ExcelProperty("浏览器")
	private String requestUri;
	@ExcelProperty("操作方式")
	private String method;
	@ExcelProperty("提交数据")
	private String params;
	@ExcelProperty("执行时间")
	private Long time;
	@ExcelProperty("异常信息")
	private String exception;
	@ExcelProperty("应用标识")
	private String serviceId;
	@TableLogic
	@ExcelIgnore
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Log() {
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getLogType() {
		return this.logType;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getTitle() {
		return this.title;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getRemoteAddr() {
		return this.remoteAddr;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUserAgent() {
		return this.userAgent;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getRequestUri() {
		return this.requestUri;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getMethod() {
		return this.method;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getParams() {
		return this.params;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getTime() {
		return this.time;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getException() {
		return this.exception;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getServiceId() {
		return this.serviceId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setId(final Long id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setLogType(final String logType) {
		this.logType = logType;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setTitle(final String title) {
		this.title = title;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRemoteAddr(final String remoteAddr) {
		this.remoteAddr = remoteAddr;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUserAgent(final String userAgent) {
		this.userAgent = userAgent;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRequestUri(final String requestUri) {
		this.requestUri = requestUri;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setMethod(final String method) {
		this.method = method;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setParams(final String params) {
		this.params = params;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setTime(final Long time) {
		this.time = time;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setException(final String exception) {
		this.exception = exception;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setServiceId(final String serviceId) {
		this.serviceId = serviceId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Log)) return false;
		final Log other = (Log) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$time = this.getTime();
		final java.lang.Object other$time = other.getTime();
		if (this$time == null ? other$time != null : !this$time.equals(other$time)) return false;
		final java.lang.Object this$logType = this.getLogType();
		final java.lang.Object other$logType = other.getLogType();
		if (this$logType == null ? other$logType != null : !this$logType.equals(other$logType)) return false;
		final java.lang.Object this$title = this.getTitle();
		final java.lang.Object other$title = other.getTitle();
		if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		final java.lang.Object this$remoteAddr = this.getRemoteAddr();
		final java.lang.Object other$remoteAddr = other.getRemoteAddr();
		if (this$remoteAddr == null ? other$remoteAddr != null : !this$remoteAddr.equals(other$remoteAddr)) return false;
		final java.lang.Object this$userAgent = this.getUserAgent();
		final java.lang.Object other$userAgent = other.getUserAgent();
		if (this$userAgent == null ? other$userAgent != null : !this$userAgent.equals(other$userAgent)) return false;
		final java.lang.Object this$requestUri = this.getRequestUri();
		final java.lang.Object other$requestUri = other.getRequestUri();
		if (this$requestUri == null ? other$requestUri != null : !this$requestUri.equals(other$requestUri)) return false;
		final java.lang.Object this$method = this.getMethod();
		final java.lang.Object other$method = other.getMethod();
		if (this$method == null ? other$method != null : !this$method.equals(other$method)) return false;
		final java.lang.Object this$params = this.getParams();
		final java.lang.Object other$params = other.getParams();
		if (this$params == null ? other$params != null : !this$params.equals(other$params)) return false;
		final java.lang.Object this$exception = this.getException();
		final java.lang.Object other$exception = other.getException();
		if (this$exception == null ? other$exception != null : !this$exception.equals(other$exception)) return false;
		final java.lang.Object this$serviceId = this.getServiceId();
		final java.lang.Object other$serviceId = other.getServiceId();
		if (this$serviceId == null ? other$serviceId != null : !this$serviceId.equals(other$serviceId)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Log;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $time = this.getTime();
		result = result * PRIME + ($time == null ? 43 : $time.hashCode());
		final java.lang.Object $logType = this.getLogType();
		result = result * PRIME + ($logType == null ? 43 : $logType.hashCode());
		final java.lang.Object $title = this.getTitle();
		result = result * PRIME + ($title == null ? 43 : $title.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		final java.lang.Object $remoteAddr = this.getRemoteAddr();
		result = result * PRIME + ($remoteAddr == null ? 43 : $remoteAddr.hashCode());
		final java.lang.Object $userAgent = this.getUserAgent();
		result = result * PRIME + ($userAgent == null ? 43 : $userAgent.hashCode());
		final java.lang.Object $requestUri = this.getRequestUri();
		result = result * PRIME + ($requestUri == null ? 43 : $requestUri.hashCode());
		final java.lang.Object $method = this.getMethod();
		result = result * PRIME + ($method == null ? 43 : $method.hashCode());
		final java.lang.Object $params = this.getParams();
		result = result * PRIME + ($params == null ? 43 : $params.hashCode());
		final java.lang.Object $exception = this.getException();
		result = result * PRIME + ($exception == null ? 43 : $exception.hashCode());
		final java.lang.Object $serviceId = this.getServiceId();
		result = result * PRIME + ($serviceId == null ? 43 : $serviceId.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "Log(id=" + this.getId() + ", logType=" + this.getLogType() + ", title=" + this.getTitle() + ", createBy=" + this.getCreateBy() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", remoteAddr=" + this.getRemoteAddr() + ", userAgent=" + this.getUserAgent() + ", requestUri=" + this.getRequestUri() + ", method=" + this.getMethod() + ", params=" + this.getParams() + ", time=" + this.getTime() + ", exception=" + this.getException() + ", serviceId=" + this.getServiceId() + ", delFlag=" + this.getDelFlag() + ")";
	}
}
