// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *
 *      Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 *  this list of conditions and the following disclaimer.
 *  Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  Neither the name of the pig4cloud.com developer nor the names of its
 *  contributors may be used to endorse or promote products derived from
 *  this software without specific prior written permission.
 *  Author: lengleng (wangiegie@gmail.com)
 *
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;
import java.time.LocalDateTime;

/**
 * <p>
 * 菜单权限表
 * </p>
 *
 * @author lengleng
 * @since 2017-11-08
 */
public class Menu extends Model<Menu> {
	@Serial
	private static final long serialVersionUID = 1L;
	/**
	 * 菜单ID
	 */
	@TableId(value = "menu_id", type = IdType.ASSIGN_ID)
	private Long menuId;
	/**
	 * 菜单名称
	 */
	private String name;
	/**
	 * 菜单名称
	 */
	private String enName;
	/**
	 * 菜单权限标识
	 */
	private String permission;
	/**
	 * 父菜单ID
	 */
	private Long parentId;
	/**
	 * 图标
	 */
	private String icon;
	/**
	 * 前端路由标识路径，默认和 comment 保持一致 过期
	 */
	private String path;
	/**
	 * 菜单显示隐藏控制
	 */
	private String visible;
	/**
	 * 排序值
	 */
	private Integer sortOrder;
	/**
	 * 菜单类型 （0菜单 1按钮）
	 */
	private String menuType;
	/**
	 * 路由缓冲
	 */
	private String keepAlive;
	private String embedded;
	/**
	 * 创建人
	 */
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	/**
	 * 修改人
	 */
	@TableField(fill = FieldFill.UPDATE)
	private String updateBy;
	/**
	 * 创建时间
	 */
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	/**
	 * 更新时间
	 */
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;
	/**
	 * 0--正常 1--删除
	 */
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Menu() {
	}

	/**
	 * 菜单ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getMenuId() {
		return this.menuId;
	}

	/**
	 * 菜单名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getName() {
		return this.name;
	}

	/**
	 * 菜单名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getEnName() {
		return this.enName;
	}

	/**
	 * 菜单权限标识
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPermission() {
		return this.permission;
	}

	/**
	 * 父菜单ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getParentId() {
		return this.parentId;
	}

	/**
	 * 图标
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getIcon() {
		return this.icon;
	}

	/**
	 * 前端路由标识路径，默认和 comment 保持一致 过期
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPath() {
		return this.path;
	}

	/**
	 * 菜单显示隐藏控制
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getVisible() {
		return this.visible;
	}

	/**
	 * 排序值
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	/**
	 * 菜单类型 （0菜单 1按钮）
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getMenuType() {
		return this.menuType;
	}

	/**
	 * 路由缓冲
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getKeepAlive() {
		return this.keepAlive;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getEmbedded() {
		return this.embedded;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * 0--正常 1--删除
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * 菜单ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setMenuId(final Long menuId) {
		this.menuId = menuId;
	}

	/**
	 * 菜单名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setName(final String name) {
		this.name = name;
	}

	/**
	 * 菜单名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setEnName(final String enName) {
		this.enName = enName;
	}

	/**
	 * 菜单权限标识
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPermission(final String permission) {
		this.permission = permission;
	}

	/**
	 * 父菜单ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setParentId(final Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * 图标
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setIcon(final String icon) {
		this.icon = icon;
	}

	/**
	 * 前端路由标识路径，默认和 comment 保持一致 过期
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPath(final String path) {
		this.path = path;
	}

	/**
	 * 菜单显示隐藏控制
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setVisible(final String visible) {
		this.visible = visible;
	}

	/**
	 * 排序值
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setSortOrder(final Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * 菜单类型 （0菜单 1按钮）
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setMenuType(final String menuType) {
		this.menuType = menuType;
	}

	/**
	 * 路由缓冲
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setKeepAlive(final String keepAlive) {
		this.keepAlive = keepAlive;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setEmbedded(final String embedded) {
		this.embedded = embedded;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * 0--正常 1--删除
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "Menu(menuId=" + this.getMenuId() + ", name=" + this.getName() + ", enName=" + this.getEnName() + ", permission=" + this.getPermission() + ", parentId=" + this.getParentId() + ", icon=" + this.getIcon() + ", path=" + this.getPath() + ", visible=" + this.getVisible() + ", sortOrder=" + this.getSortOrder() + ", menuType=" + this.getMenuType() + ", keepAlive=" + this.getKeepAlive() + ", embedded=" + this.getEmbedded() + ", createBy=" + this.getCreateBy() + ", updateBy=" + this.getUpdateBy() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", delFlag=" + this.getDelFlag() + ")";
	}


	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public static final class Fields {
		public static final java.lang.String menuId = "menuId";
		public static final java.lang.String name = "name";
		public static final java.lang.String enName = "enName";
		public static final java.lang.String permission = "permission";
		public static final java.lang.String parentId = "parentId";
		public static final java.lang.String icon = "icon";
		public static final java.lang.String path = "path";
		public static final java.lang.String visible = "visible";
		public static final java.lang.String sortOrder = "sortOrder";
		public static final java.lang.String menuType = "menuType";
		public static final java.lang.String keepAlive = "keepAlive";
		public static final java.lang.String embedded = "embedded";
		public static final java.lang.String createBy = "createBy";
		public static final java.lang.String updateBy = "updateBy";
		public static final java.lang.String createTime = "createTime";
		public static final java.lang.String updateTime = "updateTime";
		public static final java.lang.String delFlag = "delFlag";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Menu)) return false;
		final Menu other = (Menu) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$menuId = this.getMenuId();
		final java.lang.Object other$menuId = other.getMenuId();
		if (this$menuId == null ? other$menuId != null : !this$menuId.equals(other$menuId)) return false;
		final java.lang.Object this$parentId = this.getParentId();
		final java.lang.Object other$parentId = other.getParentId();
		if (this$parentId == null ? other$parentId != null : !this$parentId.equals(other$parentId)) return false;
		final java.lang.Object this$sortOrder = this.getSortOrder();
		final java.lang.Object other$sortOrder = other.getSortOrder();
		if (this$sortOrder == null ? other$sortOrder != null : !this$sortOrder.equals(other$sortOrder)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		final java.lang.Object this$enName = this.getEnName();
		final java.lang.Object other$enName = other.getEnName();
		if (this$enName == null ? other$enName != null : !this$enName.equals(other$enName)) return false;
		final java.lang.Object this$permission = this.getPermission();
		final java.lang.Object other$permission = other.getPermission();
		if (this$permission == null ? other$permission != null : !this$permission.equals(other$permission)) return false;
		final java.lang.Object this$icon = this.getIcon();
		final java.lang.Object other$icon = other.getIcon();
		if (this$icon == null ? other$icon != null : !this$icon.equals(other$icon)) return false;
		final java.lang.Object this$path = this.getPath();
		final java.lang.Object other$path = other.getPath();
		if (this$path == null ? other$path != null : !this$path.equals(other$path)) return false;
		final java.lang.Object this$visible = this.getVisible();
		final java.lang.Object other$visible = other.getVisible();
		if (this$visible == null ? other$visible != null : !this$visible.equals(other$visible)) return false;
		final java.lang.Object this$menuType = this.getMenuType();
		final java.lang.Object other$menuType = other.getMenuType();
		if (this$menuType == null ? other$menuType != null : !this$menuType.equals(other$menuType)) return false;
		final java.lang.Object this$keepAlive = this.getKeepAlive();
		final java.lang.Object other$keepAlive = other.getKeepAlive();
		if (this$keepAlive == null ? other$keepAlive != null : !this$keepAlive.equals(other$keepAlive)) return false;
		final java.lang.Object this$embedded = this.getEmbedded();
		final java.lang.Object other$embedded = other.getEmbedded();
		if (this$embedded == null ? other$embedded != null : !this$embedded.equals(other$embedded)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Menu;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $menuId = this.getMenuId();
		result = result * PRIME + ($menuId == null ? 43 : $menuId.hashCode());
		final java.lang.Object $parentId = this.getParentId();
		result = result * PRIME + ($parentId == null ? 43 : $parentId.hashCode());
		final java.lang.Object $sortOrder = this.getSortOrder();
		result = result * PRIME + ($sortOrder == null ? 43 : $sortOrder.hashCode());
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		final java.lang.Object $enName = this.getEnName();
		result = result * PRIME + ($enName == null ? 43 : $enName.hashCode());
		final java.lang.Object $permission = this.getPermission();
		result = result * PRIME + ($permission == null ? 43 : $permission.hashCode());
		final java.lang.Object $icon = this.getIcon();
		result = result * PRIME + ($icon == null ? 43 : $icon.hashCode());
		final java.lang.Object $path = this.getPath();
		result = result * PRIME + ($path == null ? 43 : $path.hashCode());
		final java.lang.Object $visible = this.getVisible();
		result = result * PRIME + ($visible == null ? 43 : $visible.hashCode());
		final java.lang.Object $menuType = this.getMenuType();
		result = result * PRIME + ($menuType == null ? 43 : $menuType.hashCode());
		final java.lang.Object $keepAlive = this.getKeepAlive();
		result = result * PRIME + ($keepAlive == null ? 43 : $keepAlive.hashCode());
		final java.lang.Object $embedded = this.getEmbedded();
		result = result * PRIME + ($embedded == null ? 43 : $embedded.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		return result;
	}
}
