// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *
 *      Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 *  this list of conditions and the following disclaimer.
 *  Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  Neither the name of the pig4cloud.com developer nor the names of its
 *  contributors may be used to endorse or promote products derived from
 *  this software without specific prior written permission.
 *  Author: lengleng (wangiegie@gmail.com)
 *
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;
import java.time.LocalDateTime;

/**
 * <p>
 * 客户端信息
 * </p>
 *
 * @author lengleng
 * @since 2018-05-15
 */
public class OauthClientDetails extends Model<OauthClientDetails> {
	@Serial
	private static final long serialVersionUID = 1L;
	@TableId(value = "id", type = IdType.ASSIGN_ID)
	private Long id;
	private String clientId;
	private String clientSecret;
	private String resourceIds;
	private String scope;
	private String[] authorizedGrantTypes;
	private String webServerRedirectUri;
	private String authorities;
	private Integer accessTokenValidity;
	private Integer refreshTokenValidity;
	private String additionalInformation;
	private String autoapprove;
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	@TableField(fill = FieldFill.UPDATE)
	private String updateBy;
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public OauthClientDetails() {
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getClientId() {
		return this.clientId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getClientSecret() {
		return this.clientSecret;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getResourceIds() {
		return this.resourceIds;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getScope() {
		return this.scope;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String[] getAuthorizedGrantTypes() {
		return this.authorizedGrantTypes;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getWebServerRedirectUri() {
		return this.webServerRedirectUri;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getAuthorities() {
		return this.authorities;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Integer getAccessTokenValidity() {
		return this.accessTokenValidity;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Integer getRefreshTokenValidity() {
		return this.refreshTokenValidity;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getAdditionalInformation() {
		return this.additionalInformation;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getAutoapprove() {
		return this.autoapprove;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setId(final Long id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setClientId(final String clientId) {
		this.clientId = clientId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setClientSecret(final String clientSecret) {
		this.clientSecret = clientSecret;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setResourceIds(final String resourceIds) {
		this.resourceIds = resourceIds;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setScope(final String scope) {
		this.scope = scope;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setAuthorizedGrantTypes(final String[] authorizedGrantTypes) {
		this.authorizedGrantTypes = authorizedGrantTypes;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setWebServerRedirectUri(final String webServerRedirectUri) {
		this.webServerRedirectUri = webServerRedirectUri;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setAuthorities(final String authorities) {
		this.authorities = authorities;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setAccessTokenValidity(final Integer accessTokenValidity) {
		this.accessTokenValidity = accessTokenValidity;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRefreshTokenValidity(final Integer refreshTokenValidity) {
		this.refreshTokenValidity = refreshTokenValidity;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setAdditionalInformation(final String additionalInformation) {
		this.additionalInformation = additionalInformation;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setAutoapprove(final String autoapprove) {
		this.autoapprove = autoapprove;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "OauthClientDetails(id=" + this.getId() + ", clientId=" + this.getClientId() + ", clientSecret=" + this.getClientSecret() + ", resourceIds=" + this.getResourceIds() + ", scope=" + this.getScope() + ", authorizedGrantTypes=" + java.util.Arrays.deepToString(this.getAuthorizedGrantTypes()) + ", webServerRedirectUri=" + this.getWebServerRedirectUri() + ", authorities=" + this.getAuthorities() + ", accessTokenValidity=" + this.getAccessTokenValidity() + ", refreshTokenValidity=" + this.getRefreshTokenValidity() + ", additionalInformation=" + this.getAdditionalInformation() + ", autoapprove=" + this.getAutoapprove() + ", delFlag=" + this.getDelFlag() + ", createBy=" + this.getCreateBy() + ", updateBy=" + this.getUpdateBy() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof OauthClientDetails)) return false;
		final OauthClientDetails other = (OauthClientDetails) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$accessTokenValidity = this.getAccessTokenValidity();
		final java.lang.Object other$accessTokenValidity = other.getAccessTokenValidity();
		if (this$accessTokenValidity == null ? other$accessTokenValidity != null : !this$accessTokenValidity.equals(other$accessTokenValidity)) return false;
		final java.lang.Object this$refreshTokenValidity = this.getRefreshTokenValidity();
		final java.lang.Object other$refreshTokenValidity = other.getRefreshTokenValidity();
		if (this$refreshTokenValidity == null ? other$refreshTokenValidity != null : !this$refreshTokenValidity.equals(other$refreshTokenValidity)) return false;
		final java.lang.Object this$clientId = this.getClientId();
		final java.lang.Object other$clientId = other.getClientId();
		if (this$clientId == null ? other$clientId != null : !this$clientId.equals(other$clientId)) return false;
		final java.lang.Object this$clientSecret = this.getClientSecret();
		final java.lang.Object other$clientSecret = other.getClientSecret();
		if (this$clientSecret == null ? other$clientSecret != null : !this$clientSecret.equals(other$clientSecret)) return false;
		final java.lang.Object this$resourceIds = this.getResourceIds();
		final java.lang.Object other$resourceIds = other.getResourceIds();
		if (this$resourceIds == null ? other$resourceIds != null : !this$resourceIds.equals(other$resourceIds)) return false;
		final java.lang.Object this$scope = this.getScope();
		final java.lang.Object other$scope = other.getScope();
		if (this$scope == null ? other$scope != null : !this$scope.equals(other$scope)) return false;
		if (!java.util.Arrays.deepEquals(this.getAuthorizedGrantTypes(), other.getAuthorizedGrantTypes())) return false;
		final java.lang.Object this$webServerRedirectUri = this.getWebServerRedirectUri();
		final java.lang.Object other$webServerRedirectUri = other.getWebServerRedirectUri();
		if (this$webServerRedirectUri == null ? other$webServerRedirectUri != null : !this$webServerRedirectUri.equals(other$webServerRedirectUri)) return false;
		final java.lang.Object this$authorities = this.getAuthorities();
		final java.lang.Object other$authorities = other.getAuthorities();
		if (this$authorities == null ? other$authorities != null : !this$authorities.equals(other$authorities)) return false;
		final java.lang.Object this$additionalInformation = this.getAdditionalInformation();
		final java.lang.Object other$additionalInformation = other.getAdditionalInformation();
		if (this$additionalInformation == null ? other$additionalInformation != null : !this$additionalInformation.equals(other$additionalInformation)) return false;
		final java.lang.Object this$autoapprove = this.getAutoapprove();
		final java.lang.Object other$autoapprove = other.getAutoapprove();
		if (this$autoapprove == null ? other$autoapprove != null : !this$autoapprove.equals(other$autoapprove)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof OauthClientDetails;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $accessTokenValidity = this.getAccessTokenValidity();
		result = result * PRIME + ($accessTokenValidity == null ? 43 : $accessTokenValidity.hashCode());
		final java.lang.Object $refreshTokenValidity = this.getRefreshTokenValidity();
		result = result * PRIME + ($refreshTokenValidity == null ? 43 : $refreshTokenValidity.hashCode());
		final java.lang.Object $clientId = this.getClientId();
		result = result * PRIME + ($clientId == null ? 43 : $clientId.hashCode());
		final java.lang.Object $clientSecret = this.getClientSecret();
		result = result * PRIME + ($clientSecret == null ? 43 : $clientSecret.hashCode());
		final java.lang.Object $resourceIds = this.getResourceIds();
		result = result * PRIME + ($resourceIds == null ? 43 : $resourceIds.hashCode());
		final java.lang.Object $scope = this.getScope();
		result = result * PRIME + ($scope == null ? 43 : $scope.hashCode());
		result = result * PRIME + java.util.Arrays.deepHashCode(this.getAuthorizedGrantTypes());
		final java.lang.Object $webServerRedirectUri = this.getWebServerRedirectUri();
		result = result * PRIME + ($webServerRedirectUri == null ? 43 : $webServerRedirectUri.hashCode());
		final java.lang.Object $authorities = this.getAuthorities();
		result = result * PRIME + ($authorities == null ? 43 : $authorities.hashCode());
		final java.lang.Object $additionalInformation = this.getAdditionalInformation();
		result = result * PRIME + ($additionalInformation == null ? 43 : $additionalInformation.hashCode());
		final java.lang.Object $autoapprove = this.getAutoapprove();
		result = result * PRIME + ($autoapprove == null ? 43 : $autoapprove.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		return result;
	}
}
