// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *    Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * Neither the name of the pig4cloud.com developer nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * Author: lengleng (wangiegie@gmail.com)
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;
import java.time.LocalDateTime;

/**
 * 岗位信息表
 *
 * @author fxz
 * @date 2022-03-26 12:50:43
 */
@TableName("sys_post")
public class Post extends Model<Post> {
	@Serial
	private static final long serialVersionUID = 1L;
	/**
	 * 岗位ID
	 */
	@TableId(value = "post_id", type = IdType.ASSIGN_ID)
	private Long postId;
	/**
	 * 岗位编码
	 */
	private String postCode;
	/**
	 * 岗位名称
	 */
	private String postName;
	/**
	 * 岗位排序
	 */
	private Integer postSort;
	/**
	 * 岗位描述
	 */
	private String remark;
	/**
	 * 创建人
	 */
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	/**
	 * 修改人
	 */
	@TableField(fill = FieldFill.UPDATE)
	private String updateBy;
	/**
	 * 是否删除 -1：已删除 0：正常
	 */
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;
	/**
	 * 创建时间
	 */
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	/**
	 * 更新时间
	 */
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Post() {
	}

	/**
	 * 岗位ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getPostId() {
		return this.postId;
	}

	/**
	 * 岗位编码
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPostCode() {
		return this.postCode;
	}

	/**
	 * 岗位名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPostName() {
		return this.postName;
	}

	/**
	 * 岗位排序
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Integer getPostSort() {
		return this.postSort;
	}

	/**
	 * 岗位描述
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getRemark() {
		return this.remark;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * 是否删除 -1：已删除 0：正常
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * 岗位ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPostId(final Long postId) {
		this.postId = postId;
	}

	/**
	 * 岗位编码
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPostCode(final String postCode) {
		this.postCode = postCode;
	}

	/**
	 * 岗位名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPostName(final String postName) {
		this.postName = postName;
	}

	/**
	 * 岗位排序
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPostSort(final Integer postSort) {
		this.postSort = postSort;
	}

	/**
	 * 岗位描述
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRemark(final String remark) {
		this.remark = remark;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * 是否删除 -1：已删除 0：正常
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "Post(postId=" + this.getPostId() + ", postCode=" + this.getPostCode() + ", postName=" + this.getPostName() + ", postSort=" + this.getPostSort() + ", remark=" + this.getRemark() + ", createBy=" + this.getCreateBy() + ", updateBy=" + this.getUpdateBy() + ", delFlag=" + this.getDelFlag() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Post)) return false;
		final Post other = (Post) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$postId = this.getPostId();
		final java.lang.Object other$postId = other.getPostId();
		if (this$postId == null ? other$postId != null : !this$postId.equals(other$postId)) return false;
		final java.lang.Object this$postSort = this.getPostSort();
		final java.lang.Object other$postSort = other.getPostSort();
		if (this$postSort == null ? other$postSort != null : !this$postSort.equals(other$postSort)) return false;
		final java.lang.Object this$postCode = this.getPostCode();
		final java.lang.Object other$postCode = other.getPostCode();
		if (this$postCode == null ? other$postCode != null : !this$postCode.equals(other$postCode)) return false;
		final java.lang.Object this$postName = this.getPostName();
		final java.lang.Object other$postName = other.getPostName();
		if (this$postName == null ? other$postName != null : !this$postName.equals(other$postName)) return false;
		final java.lang.Object this$remark = this.getRemark();
		final java.lang.Object other$remark = other.getRemark();
		if (this$remark == null ? other$remark != null : !this$remark.equals(other$remark)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Post;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $postId = this.getPostId();
		result = result * PRIME + ($postId == null ? 43 : $postId.hashCode());
		final java.lang.Object $postSort = this.getPostSort();
		result = result * PRIME + ($postSort == null ? 43 : $postSort.hashCode());
		final java.lang.Object $postCode = this.getPostCode();
		result = result * PRIME + ($postCode == null ? 43 : $postCode.hashCode());
		final java.lang.Object $postName = this.getPostName();
		result = result * PRIME + ($postName == null ? 43 : $postName.hashCode());
		final java.lang.Object $remark = this.getRemark();
		result = result * PRIME + ($remark == null ? 43 : $remark.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		return result;
	}
}
