// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *    Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * Neither the name of the pig4cloud.com developer nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * Author: lengleng (wangiegie@gmail.com)
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;
import java.time.LocalDateTime;

/**
 * 公共参数配置
 *
 * @author Lucky
 * @date 2019-04-29
 */
public class PublicParam extends Model<PublicParam> {
	@Serial
	private static final long serialVersionUID = 1L;
	/**
	 * 编号
	 */
	@TableId(type = IdType.ASSIGN_ID)
	private Long publicId;
	/**
	 * 公共参数名称
	 */
	private String publicName;
	/**
	 * 公共参数地址值,英文大写+下划线
	 */
	private String publicKey;
	/**
	 * 值
	 */
	private String publicValue;
	/**
	 * 状态（1有效；2无效；）
	 */
	private String status;
	/**
	 * 公共参数编码
	 */
	private String validateCode;
	/**
	 * 是否是系统内置
	 */
	private String systemFlag;
	/**
	 * 配置类型：0-默认；1-检索；2-原文；3-报表；4-安全；5-文档；6-消息；9-其他
	 */
	private String publicType;
	/**
	 * 创建人
	 */
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	/**
	 * 修改人
	 */
	@TableField(fill = FieldFill.UPDATE)
	private String updateBy;
	/**
	 * 删除标记
	 */
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;
	/**
	 * 创建时间
	 */
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	/**
	 * 更新时间
	 */
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public PublicParam() {
	}

	/**
	 * 编号
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getPublicId() {
		return this.publicId;
	}

	/**
	 * 公共参数名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPublicName() {
		return this.publicName;
	}

	/**
	 * 公共参数地址值,英文大写+下划线
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPublicKey() {
		return this.publicKey;
	}

	/**
	 * 值
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPublicValue() {
		return this.publicValue;
	}

	/**
	 * 状态（1有效；2无效；）
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getStatus() {
		return this.status;
	}

	/**
	 * 公共参数编码
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getValidateCode() {
		return this.validateCode;
	}

	/**
	 * 是否是系统内置
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getSystemFlag() {
		return this.systemFlag;
	}

	/**
	 * 配置类型：0-默认；1-检索；2-原文；3-报表；4-安全；5-文档；6-消息；9-其他
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPublicType() {
		return this.publicType;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * 删除标记
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * 编号
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPublicId(final Long publicId) {
		this.publicId = publicId;
	}

	/**
	 * 公共参数名称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPublicName(final String publicName) {
		this.publicName = publicName;
	}

	/**
	 * 公共参数地址值,英文大写+下划线
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPublicKey(final String publicKey) {
		this.publicKey = publicKey;
	}

	/**
	 * 值
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPublicValue(final String publicValue) {
		this.publicValue = publicValue;
	}

	/**
	 * 状态（1有效；2无效；）
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setStatus(final String status) {
		this.status = status;
	}

	/**
	 * 公共参数编码
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setValidateCode(final String validateCode) {
		this.validateCode = validateCode;
	}

	/**
	 * 是否是系统内置
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setSystemFlag(final String systemFlag) {
		this.systemFlag = systemFlag;
	}

	/**
	 * 配置类型：0-默认；1-检索；2-原文；3-报表；4-安全；5-文档；6-消息；9-其他
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPublicType(final String publicType) {
		this.publicType = publicType;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * 删除标记
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	/**
	 * 更新时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "PublicParam(publicId=" + this.getPublicId() + ", publicName=" + this.getPublicName() + ", publicKey=" + this.getPublicKey() + ", publicValue=" + this.getPublicValue() + ", status=" + this.getStatus() + ", validateCode=" + this.getValidateCode() + ", systemFlag=" + this.getSystemFlag() + ", publicType=" + this.getPublicType() + ", createBy=" + this.getCreateBy() + ", updateBy=" + this.getUpdateBy() + ", delFlag=" + this.getDelFlag() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof PublicParam)) return false;
		final PublicParam other = (PublicParam) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$publicId = this.getPublicId();
		final java.lang.Object other$publicId = other.getPublicId();
		if (this$publicId == null ? other$publicId != null : !this$publicId.equals(other$publicId)) return false;
		final java.lang.Object this$publicName = this.getPublicName();
		final java.lang.Object other$publicName = other.getPublicName();
		if (this$publicName == null ? other$publicName != null : !this$publicName.equals(other$publicName)) return false;
		final java.lang.Object this$publicKey = this.getPublicKey();
		final java.lang.Object other$publicKey = other.getPublicKey();
		if (this$publicKey == null ? other$publicKey != null : !this$publicKey.equals(other$publicKey)) return false;
		final java.lang.Object this$publicValue = this.getPublicValue();
		final java.lang.Object other$publicValue = other.getPublicValue();
		if (this$publicValue == null ? other$publicValue != null : !this$publicValue.equals(other$publicValue)) return false;
		final java.lang.Object this$status = this.getStatus();
		final java.lang.Object other$status = other.getStatus();
		if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
		final java.lang.Object this$validateCode = this.getValidateCode();
		final java.lang.Object other$validateCode = other.getValidateCode();
		if (this$validateCode == null ? other$validateCode != null : !this$validateCode.equals(other$validateCode)) return false;
		final java.lang.Object this$systemFlag = this.getSystemFlag();
		final java.lang.Object other$systemFlag = other.getSystemFlag();
		if (this$systemFlag == null ? other$systemFlag != null : !this$systemFlag.equals(other$systemFlag)) return false;
		final java.lang.Object this$publicType = this.getPublicType();
		final java.lang.Object other$publicType = other.getPublicType();
		if (this$publicType == null ? other$publicType != null : !this$publicType.equals(other$publicType)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof PublicParam;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $publicId = this.getPublicId();
		result = result * PRIME + ($publicId == null ? 43 : $publicId.hashCode());
		final java.lang.Object $publicName = this.getPublicName();
		result = result * PRIME + ($publicName == null ? 43 : $publicName.hashCode());
		final java.lang.Object $publicKey = this.getPublicKey();
		result = result * PRIME + ($publicKey == null ? 43 : $publicKey.hashCode());
		final java.lang.Object $publicValue = this.getPublicValue();
		result = result * PRIME + ($publicValue == null ? 43 : $publicValue.hashCode());
		final java.lang.Object $status = this.getStatus();
		result = result * PRIME + ($status == null ? 43 : $status.hashCode());
		final java.lang.Object $validateCode = this.getValidateCode();
		result = result * PRIME + ($validateCode == null ? 43 : $validateCode.hashCode());
		final java.lang.Object $systemFlag = this.getSystemFlag();
		result = result * PRIME + ($systemFlag == null ? 43 : $systemFlag.hashCode());
		final java.lang.Object $publicType = this.getPublicType();
		result = result * PRIME + ($publicType == null ? 43 : $publicType.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		return result;
	}
}
