// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *
 *      Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 *  this list of conditions and the following disclaimer.
 *  Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  Neither the name of the pig4cloud.com developer nor the names of its
 *  contributors may be used to endorse or promote products derived from
 *  this software without specific prior written permission.
 *  Author: lengleng (wangiegie@gmail.com)
 *
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;
import java.time.LocalDateTime;

/**
 * <p>
 * 角色表
 * </p>
 *
 * @author lengleng
 * @since 2017-10-29
 */
public class Role extends Model<Role> {
	@Serial
	private static final long serialVersionUID = 1L;
	@TableId(value = "role_id", type = IdType.ASSIGN_ID)
	private Long roleId;
	private String roleName;
	private String roleCode;
	private String roleDesc;
	/**
	 * 创建人
	 */
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	/**
	 * 修改人
	 */
	@TableField(fill = FieldFill.UPDATE)
	private String updateBy;
	/**
	 * 创建时间
	 */
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	/**
	 * 修改时间
	 */
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;
	/**
	 * 删除标识（0-正常,1-删除）
	 */
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Role() {
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getRoleId() {
		return this.roleId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getRoleName() {
		return this.roleName;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getRoleCode() {
		return this.roleCode;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getRoleDesc() {
		return this.roleDesc;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	/**
	 * 修改时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * 删除标识（0-正常,1-删除）
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRoleId(final Long roleId) {
		this.roleId = roleId;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRoleName(final String roleName) {
		this.roleName = roleName;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRoleCode(final String roleCode) {
		this.roleCode = roleCode;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRoleDesc(final String roleDesc) {
		this.roleDesc = roleDesc;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	/**
	 * 修改时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * 删除标识（0-正常,1-删除）
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "Role(roleId=" + this.getRoleId() + ", roleName=" + this.getRoleName() + ", roleCode=" + this.getRoleCode() + ", roleDesc=" + this.getRoleDesc() + ", createBy=" + this.getCreateBy() + ", updateBy=" + this.getUpdateBy() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", delFlag=" + this.getDelFlag() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Role)) return false;
		final Role other = (Role) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$roleId = this.getRoleId();
		final java.lang.Object other$roleId = other.getRoleId();
		if (this$roleId == null ? other$roleId != null : !this$roleId.equals(other$roleId)) return false;
		final java.lang.Object this$roleName = this.getRoleName();
		final java.lang.Object other$roleName = other.getRoleName();
		if (this$roleName == null ? other$roleName != null : !this$roleName.equals(other$roleName)) return false;
		final java.lang.Object this$roleCode = this.getRoleCode();
		final java.lang.Object other$roleCode = other.getRoleCode();
		if (this$roleCode == null ? other$roleCode != null : !this$roleCode.equals(other$roleCode)) return false;
		final java.lang.Object this$roleDesc = this.getRoleDesc();
		final java.lang.Object other$roleDesc = other.getRoleDesc();
		if (this$roleDesc == null ? other$roleDesc != null : !this$roleDesc.equals(other$roleDesc)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Role;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $roleId = this.getRoleId();
		result = result * PRIME + ($roleId == null ? 43 : $roleId.hashCode());
		final java.lang.Object $roleName = this.getRoleName();
		result = result * PRIME + ($roleName == null ? 43 : $roleName.hashCode());
		final java.lang.Object $roleCode = this.getRoleCode();
		result = result * PRIME + ($roleCode == null ? 43 : $roleCode.hashCode());
		final java.lang.Object $roleDesc = this.getRoleDesc();
		result = result * PRIME + ($roleDesc == null ? 43 : $roleDesc.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		return result;
	}
}
