// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *
 *      Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 *  this list of conditions and the following disclaimer.
 *  Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  Neither the name of the pig4cloud.com developer nor the names of its
 *  contributors may be used to endorse or promote products derived from
 *  this software without specific prior written permission.
 *  Author: lengleng (wangiegie@gmail.com)
 *
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;

/**
 * <p>
 * 角色菜单表
 * </p>
 *
 * @author lengleng
 * @since 2017-10-29
 */
public class RoleMenu extends Model<RoleMenu> {
	@Serial
	private static final long serialVersionUID = 1L;
	/**
	 * 角色ID
	 */
	private Long roleId;
	/**
	 * 菜单ID
	 */
	private Long menuId;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public RoleMenu() {
	}

	/**
	 * 角色ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getRoleId() {
		return this.roleId;
	}

	/**
	 * 菜单ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getMenuId() {
		return this.menuId;
	}

	/**
	 * 角色ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRoleId(final Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * 菜单ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setMenuId(final Long menuId) {
		this.menuId = menuId;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "RoleMenu(roleId=" + this.getRoleId() + ", menuId=" + this.getMenuId() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof RoleMenu)) return false;
		final RoleMenu other = (RoleMenu) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$roleId = this.getRoleId();
		final java.lang.Object other$roleId = other.getRoleId();
		if (this$roleId == null ? other$roleId != null : !this$roleId.equals(other$roleId)) return false;
		final java.lang.Object this$menuId = this.getMenuId();
		final java.lang.Object other$menuId = other.getMenuId();
		if (this$menuId == null ? other$menuId != null : !this$menuId.equals(other$menuId)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof RoleMenu;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $roleId = this.getRoleId();
		result = result * PRIME + ($roleId == null ? 43 : $roleId.hashCode());
		final java.lang.Object $menuId = this.getMenuId();
		result = result * PRIME + ($menuId == null ? 43 : $menuId.hashCode());
		return result;
	}
}
