// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *
 *      Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 *  this list of conditions and the following disclaimer.
 *  Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  Neither the name of the pig4cloud.com developer nor the names of its
 *  contributors may be used to endorse or promote products derived from
 *  this software without specific prior written permission.
 *  Author: lengleng (wangiegie@gmail.com)
 *
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.annotation.*;
import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * <p>
 * 用户表
 * </p>
 *
 * @author lengleng
 * @since 2017-10-29
 */
public class User implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;
	/**
	 * 主键ID
	 */
	@TableId(value = "user_id", type = IdType.ASSIGN_ID)
	private Long userId;
	/**
	 * 用户名
	 */
	private String username;
	/**
	 * 密码
	 */
	private String password;
	/**
	 * 随机盐
	 */
	private String salt;
	/**
	 * 创建人
	 */
	@TableField(fill = FieldFill.INSERT)
	private String createBy;
	/**
	 * 修改人
	 */
	@TableField(fill = FieldFill.UPDATE)
	private String updateBy;
	/**
	 * 创建时间
	 */
	@TableField(fill = FieldFill.INSERT)
	private LocalDateTime createTime;
	/**
	 * 修改时间
	 */
	@TableField(fill = FieldFill.UPDATE)
	private LocalDateTime updateTime;
	/**
	 * 0-正常，1-删除
	 */
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private String delFlag;
	/**
	 * 锁定标记
	 */
	private String lockFlag;
	/**
	 * 手机号
	 */
	private String phone;
	/**
	 * 头像
	 */
	private String avatar;
	/**
	 * 部门ID
	 */
	private Long deptId;
	/**
	 * 微信openid
	 */
	private String wxOpenid;
	/**
	 * 微信小程序openId
	 */
	private String miniOpenid;
	/**
	 * QQ openid
	 */
	private String qqOpenid;
	/**
	 * 码云唯一标识
	 */
	private String giteeLogin;
	/**
	 * 开源中国唯一标识
	 */
	private String oscId;
	/**
	 * 昵称
	 */
	private String nickname;
	/**
	 * 姓名
	 */
	private String name;
	/**
	 * 邮箱
	 */
	private String email;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public User() {
	}

	/**
	 * 主键ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getUserId() {
		return this.userId;
	}

	/**
	 * 用户名
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUsername() {
		return this.username;
	}

	/**
	 * 密码
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPassword() {
		return this.password;
	}

	/**
	 * 随机盐
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getSalt() {
		return this.salt;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getCreateTime() {
		return this.createTime;
	}

	/**
	 * 修改时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * 0-正常，1-删除
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * 锁定标记
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getLockFlag() {
		return this.lockFlag;
	}

	/**
	 * 手机号
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getPhone() {
		return this.phone;
	}

	/**
	 * 头像
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getAvatar() {
		return this.avatar;
	}

	/**
	 * 部门ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getDeptId() {
		return this.deptId;
	}

	/**
	 * 微信openid
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getWxOpenid() {
		return this.wxOpenid;
	}

	/**
	 * 微信小程序openId
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getMiniOpenid() {
		return this.miniOpenid;
	}

	/**
	 * QQ openid
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getQqOpenid() {
		return this.qqOpenid;
	}

	/**
	 * 码云唯一标识
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getGiteeLogin() {
		return this.giteeLogin;
	}

	/**
	 * 开源中国唯一标识
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getOscId() {
		return this.oscId;
	}

	/**
	 * 昵称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getNickname() {
		return this.nickname;
	}

	/**
	 * 姓名
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getName() {
		return this.name;
	}

	/**
	 * 邮箱
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public String getEmail() {
		return this.email;
	}

	/**
	 * 主键ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUserId(final Long userId) {
		this.userId = userId;
	}

	/**
	 * 用户名
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUsername(final String username) {
		this.username = username;
	}

	/**
	 * 密码
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPassword(final String password) {
		this.password = password;
	}

	/**
	 * 随机盐
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setSalt(final String salt) {
		this.salt = salt;
	}

	/**
	 * 创建人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateBy(final String createBy) {
		this.createBy = createBy;
	}

	/**
	 * 修改人
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateBy(final String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * 创建时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setCreateTime(final LocalDateTime createTime) {
		this.createTime = createTime;
	}

	/**
	 * 修改时间
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUpdateTime(final LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * 0-正常，1-删除
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDelFlag(final String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * 锁定标记
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setLockFlag(final String lockFlag) {
		this.lockFlag = lockFlag;
	}

	/**
	 * 手机号
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPhone(final String phone) {
		this.phone = phone;
	}

	/**
	 * 头像
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setAvatar(final String avatar) {
		this.avatar = avatar;
	}

	/**
	 * 部门ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setDeptId(final Long deptId) {
		this.deptId = deptId;
	}

	/**
	 * 微信openid
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setWxOpenid(final String wxOpenid) {
		this.wxOpenid = wxOpenid;
	}

	/**
	 * 微信小程序openId
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setMiniOpenid(final String miniOpenid) {
		this.miniOpenid = miniOpenid;
	}

	/**
	 * QQ openid
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setQqOpenid(final String qqOpenid) {
		this.qqOpenid = qqOpenid;
	}

	/**
	 * 码云唯一标识
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setGiteeLogin(final String giteeLogin) {
		this.giteeLogin = giteeLogin;
	}

	/**
	 * 开源中国唯一标识
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setOscId(final String oscId) {
		this.oscId = oscId;
	}

	/**
	 * 昵称
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setNickname(final String nickname) {
		this.nickname = nickname;
	}

	/**
	 * 姓名
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setName(final String name) {
		this.name = name;
	}

	/**
	 * 邮箱
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setEmail(final String email) {
		this.email = email;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof User)) return false;
		final User other = (User) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$userId = this.getUserId();
		final java.lang.Object other$userId = other.getUserId();
		if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
		final java.lang.Object this$deptId = this.getDeptId();
		final java.lang.Object other$deptId = other.getDeptId();
		if (this$deptId == null ? other$deptId != null : !this$deptId.equals(other$deptId)) return false;
		final java.lang.Object this$username = this.getUsername();
		final java.lang.Object other$username = other.getUsername();
		if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
		final java.lang.Object this$password = this.getPassword();
		final java.lang.Object other$password = other.getPassword();
		if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
		final java.lang.Object this$salt = this.getSalt();
		final java.lang.Object other$salt = other.getSalt();
		if (this$salt == null ? other$salt != null : !this$salt.equals(other$salt)) return false;
		final java.lang.Object this$createBy = this.getCreateBy();
		final java.lang.Object other$createBy = other.getCreateBy();
		if (this$createBy == null ? other$createBy != null : !this$createBy.equals(other$createBy)) return false;
		final java.lang.Object this$updateBy = this.getUpdateBy();
		final java.lang.Object other$updateBy = other.getUpdateBy();
		if (this$updateBy == null ? other$updateBy != null : !this$updateBy.equals(other$updateBy)) return false;
		final java.lang.Object this$createTime = this.getCreateTime();
		final java.lang.Object other$createTime = other.getCreateTime();
		if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
		final java.lang.Object this$updateTime = this.getUpdateTime();
		final java.lang.Object other$updateTime = other.getUpdateTime();
		if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
		final java.lang.Object this$delFlag = this.getDelFlag();
		final java.lang.Object other$delFlag = other.getDelFlag();
		if (this$delFlag == null ? other$delFlag != null : !this$delFlag.equals(other$delFlag)) return false;
		final java.lang.Object this$lockFlag = this.getLockFlag();
		final java.lang.Object other$lockFlag = other.getLockFlag();
		if (this$lockFlag == null ? other$lockFlag != null : !this$lockFlag.equals(other$lockFlag)) return false;
		final java.lang.Object this$phone = this.getPhone();
		final java.lang.Object other$phone = other.getPhone();
		if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
		final java.lang.Object this$avatar = this.getAvatar();
		final java.lang.Object other$avatar = other.getAvatar();
		if (this$avatar == null ? other$avatar != null : !this$avatar.equals(other$avatar)) return false;
		final java.lang.Object this$wxOpenid = this.getWxOpenid();
		final java.lang.Object other$wxOpenid = other.getWxOpenid();
		if (this$wxOpenid == null ? other$wxOpenid != null : !this$wxOpenid.equals(other$wxOpenid)) return false;
		final java.lang.Object this$miniOpenid = this.getMiniOpenid();
		final java.lang.Object other$miniOpenid = other.getMiniOpenid();
		if (this$miniOpenid == null ? other$miniOpenid != null : !this$miniOpenid.equals(other$miniOpenid)) return false;
		final java.lang.Object this$qqOpenid = this.getQqOpenid();
		final java.lang.Object other$qqOpenid = other.getQqOpenid();
		if (this$qqOpenid == null ? other$qqOpenid != null : !this$qqOpenid.equals(other$qqOpenid)) return false;
		final java.lang.Object this$giteeLogin = this.getGiteeLogin();
		final java.lang.Object other$giteeLogin = other.getGiteeLogin();
		if (this$giteeLogin == null ? other$giteeLogin != null : !this$giteeLogin.equals(other$giteeLogin)) return false;
		final java.lang.Object this$oscId = this.getOscId();
		final java.lang.Object other$oscId = other.getOscId();
		if (this$oscId == null ? other$oscId != null : !this$oscId.equals(other$oscId)) return false;
		final java.lang.Object this$nickname = this.getNickname();
		final java.lang.Object other$nickname = other.getNickname();
		if (this$nickname == null ? other$nickname != null : !this$nickname.equals(other$nickname)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		final java.lang.Object this$email = this.getEmail();
		final java.lang.Object other$email = other.getEmail();
		if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof User;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $userId = this.getUserId();
		result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
		final java.lang.Object $deptId = this.getDeptId();
		result = result * PRIME + ($deptId == null ? 43 : $deptId.hashCode());
		final java.lang.Object $username = this.getUsername();
		result = result * PRIME + ($username == null ? 43 : $username.hashCode());
		final java.lang.Object $password = this.getPassword();
		result = result * PRIME + ($password == null ? 43 : $password.hashCode());
		final java.lang.Object $salt = this.getSalt();
		result = result * PRIME + ($salt == null ? 43 : $salt.hashCode());
		final java.lang.Object $createBy = this.getCreateBy();
		result = result * PRIME + ($createBy == null ? 43 : $createBy.hashCode());
		final java.lang.Object $updateBy = this.getUpdateBy();
		result = result * PRIME + ($updateBy == null ? 43 : $updateBy.hashCode());
		final java.lang.Object $createTime = this.getCreateTime();
		result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
		final java.lang.Object $updateTime = this.getUpdateTime();
		result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
		final java.lang.Object $delFlag = this.getDelFlag();
		result = result * PRIME + ($delFlag == null ? 43 : $delFlag.hashCode());
		final java.lang.Object $lockFlag = this.getLockFlag();
		result = result * PRIME + ($lockFlag == null ? 43 : $lockFlag.hashCode());
		final java.lang.Object $phone = this.getPhone();
		result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
		final java.lang.Object $avatar = this.getAvatar();
		result = result * PRIME + ($avatar == null ? 43 : $avatar.hashCode());
		final java.lang.Object $wxOpenid = this.getWxOpenid();
		result = result * PRIME + ($wxOpenid == null ? 43 : $wxOpenid.hashCode());
		final java.lang.Object $miniOpenid = this.getMiniOpenid();
		result = result * PRIME + ($miniOpenid == null ? 43 : $miniOpenid.hashCode());
		final java.lang.Object $qqOpenid = this.getQqOpenid();
		result = result * PRIME + ($qqOpenid == null ? 43 : $qqOpenid.hashCode());
		final java.lang.Object $giteeLogin = this.getGiteeLogin();
		result = result * PRIME + ($giteeLogin == null ? 43 : $giteeLogin.hashCode());
		final java.lang.Object $oscId = this.getOscId();
		result = result * PRIME + ($oscId == null ? 43 : $oscId.hashCode());
		final java.lang.Object $nickname = this.getNickname();
		result = result * PRIME + ($nickname == null ? 43 : $nickname.hashCode());
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		final java.lang.Object $email = this.getEmail();
		result = result * PRIME + ($email == null ? 43 : $email.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "User(userId=" + this.getUserId() + ", username=" + this.getUsername() + ", password=" + this.getPassword() + ", salt=" + this.getSalt() + ", createBy=" + this.getCreateBy() + ", updateBy=" + this.getUpdateBy() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", delFlag=" + this.getDelFlag() + ", lockFlag=" + this.getLockFlag() + ", phone=" + this.getPhone() + ", avatar=" + this.getAvatar() + ", deptId=" + this.getDeptId() + ", wxOpenid=" + this.getWxOpenid() + ", miniOpenid=" + this.getMiniOpenid() + ", qqOpenid=" + this.getQqOpenid() + ", giteeLogin=" + this.getGiteeLogin() + ", oscId=" + this.getOscId() + ", nickname=" + this.getNickname() + ", name=" + this.getName() + ", email=" + this.getEmail() + ")";
	}
}
