// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 *
 *      Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 *  this list of conditions and the following disclaimer.
 *  Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  Neither the name of the pig4cloud.com developer nor the names of its
 *  contributors may be used to endorse or promote products derived from
 *  this software without specific prior written permission.
 *  Author: lengleng (wangiegie@gmail.com)
 *
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;

/**
 * <p>
 * 用户角色表
 * </p>
 *
 * @author lengleng
 * @since 2017-10-29
 */
public class UserRole extends Model<UserRole> {
	@Serial
	private static final long serialVersionUID = 1L;
	/**
	 * 用户ID
	 */
	private Long userId;
	/**
	 * 角色ID
	 */
	private Long roleId;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public UserRole() {
	}

	/**
	 * 用户ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getUserId() {
		return this.userId;
	}

	/**
	 * 角色ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getRoleId() {
		return this.roleId;
	}

	/**
	 * 用户ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUserId(final Long userId) {
		this.userId = userId;
	}

	/**
	 * 角色ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setRoleId(final Long roleId) {
		this.roleId = roleId;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "UserRole(userId=" + this.getUserId() + ", roleId=" + this.getRoleId() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof UserRole)) return false;
		final UserRole other = (UserRole) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$userId = this.getUserId();
		final java.lang.Object other$userId = other.getUserId();
		if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
		final java.lang.Object this$roleId = this.getRoleId();
		final java.lang.Object other$roleId = other.getRoleId();
		if (this$roleId == null ? other$roleId != null : !this$roleId.equals(other$roleId)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof UserRole;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $userId = this.getUserId();
		result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
		final java.lang.Object $roleId = this.getRoleId();
		result = result * PRIME + ($roleId == null ? 43 : $roleId.hashCode());
		return result;
	}
}
