// Generated by delombok at Tue Mar 17 18:23:10 CST 2026
/*
 * Copyright (c) 2020 pig4cloud Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.pig4cloud.pig.sys.entity;

import com.baomidou.mybatisplus.extension.activerecord.Model;
import java.io.Serial;

/**
 * <p>
 * 用户岗位表
 * </p>
 *
 * @author fxz
 */
public class UserPost extends Model<UserPost> {
	@Serial
	private static final long serialVersionUID = 1L;
	/**
	 * 用户ID
	 */
	private Long userId;
	/**
	 * 岗位ID
	 */
	private Long postId;

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public UserPost() {
	}

	/**
	 * 用户ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getUserId() {
		return this.userId;
	}

	/**
	 * 岗位ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public Long getPostId() {
		return this.postId;
	}

	/**
	 * 用户ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setUserId(final Long userId) {
		this.userId = userId;
	}

	/**
	 * 岗位ID
	 */
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public void setPostId(final Long postId) {
		this.postId = postId;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "UserPost(userId=" + this.getUserId() + ", postId=" + this.getPostId() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof UserPost)) return false;
		final UserPost other = (UserPost) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$userId = this.getUserId();
		final java.lang.Object other$userId = other.getUserId();
		if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
		final java.lang.Object this$postId = this.getPostId();
		final java.lang.Object other$postId = other.getPostId();
		if (this$postId == null ? other$postId != null : !this$postId.equals(other$postId)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof UserPost;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $userId = this.getUserId();
		result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
		final java.lang.Object $postId = this.getPostId();
		result = result * PRIME + ($postId == null ? 43 : $postId.hashCode());
		return result;
	}
}
