services:
  bacon-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: bacon-mysql
    image: bacon-mysql
    ports:
      - 33306:3306
    networks:
      - spring_cloud_default

  bacon-redis:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    ports:
      - 36379:6379
    restart: always
    container_name: bacon-redis
    hostname: bacon-redis
    networks:
      - spring_cloud_default

  bacon-register:
    build:
      context: ./bacon-register
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 8080:8080
    environment:
      MYSQL_HOST: bacon-mysql
      REDIS_HOST: bacon-redis
    container_name: bacon-register
    hostname: bacon-register
    image: bacon-register
    networks:
      - spring_cloud_default

  bacon-gateway:
    build:
      context: ./bacon-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: bacon-gateway
    hostname: bacon-gateway
    image: bacon-gateway
    environment:
      REDIS_HOST: bacon-redis
      NACOS_HOST: bacon-register
    networks:
      - spring_cloud_default

  bacon-auth:
    build:
      context: ./bacon-auth
    restart: always
    container_name: bacon-auth
    hostname: bacon-auth
    image: bacon-auth
    environment:
      REDIS_HOST: bacon-redis
      NACOS_HOST: bacon-register
    networks:
      - spring_cloud_default

  bacon-upms:
    build:
      context: ./bacon-upms/bacon-upms-biz
    restart: always
    container_name: bacon-upms
    hostname: bacon-upms
    image: bacon-upms
    environment:
      MYSQL_HOST: bacon-mysql
      REDIS_HOST: bacon-redis
      NACOS_HOST: bacon-register
    networks:
      - spring_cloud_default

  bacon-monitor:
    build:
      context: ./bacon-visual/bacon-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: bacon-monitor
    hostname: bacon-monitor
    image: bacon-monitor
    environment:
      NACOS_HOST: bacon-register
    networks:
      - spring_cloud_default

  bacon-codegen:
    build:
      context: ./bacon-visual/bacon-codegen
    restart: always
    container_name: bacon-codegen
    hostname: bacon-codegen
    image: bacon-codegen
    environment:
      MYSQL_HOST: bacon-mysql
      REDIS_HOST: bacon-redis
      NACOS_HOST: bacon-register
    networks:
      - spring_cloud_default

  bacon-quartz:
    build:
      context: ./bacon-visual/bacon-quartz
    restart: always
    image: bacon-quartz
    container_name: bacon-quartz
    environment:
      MYSQL_HOST: bacon-mysql
      REDIS_HOST: bacon-redis
      NACOS_HOST: bacon-register
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
